management:
  endpoint:
    health:
      show-details: always
      group:
        liveness:
          show-details: always
        readiness:
          show-details: always

logging:
  structured:
    format:
      console: none
  level:
    io.github.romarioteles.citizenservices: DEBUG

spring:
  web:
    error:
      include-message: always
      include-binding-errors: always
      include-stacktrace: on_param
